import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from './contexts/UserContext';
import { useUser } from "./contexts/UserContext";
import { getSession } from "@/libs/getSession";
import { getUser } from "@/action/user";
import { SessionProvider } from "next-auth/react";

/*
export const metadata: Metadata = {
  title: "Fashion App",
  description: "Generated by create next app",
};
*/

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
/*
  const session = await getSession();
  const user = session?.user;
  // Checks if the usr is logged in to display proper nav
  const isIn = user ? true : false;
  const userEmail = isIn ? session?.user?.email : null;
  
  const { email, isLoggedIn, login, logout } = useUser();
  login(userEmail);
  console.log(userEmail);
*/

  return (
    
    <html lang="en">
      <body className="bg-background">
        {children}
      </body>
    </html>
    
  );
}


